apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "login-app.fullname" . }}-config
  labels:
    {{- include "login-app.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: {{ .Values.postgresql.host | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.port | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.username | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
